/**
 * ESLint flat config. Run: npm run lint
 * server/public/app.js is generated – do not edit; it is ignored here.
 */
const BROWSER_GLOBALS = {
  window: 'readonly',
  document: 'readonly',
  fetch: 'readonly',
  setTimeout: 'readonly',
  clearTimeout: 'readonly',
  setInterval: 'readonly',
  clearInterval: 'readonly',
  requestAnimationFrame: 'readonly',
  CustomEvent: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  FormData: 'readonly',
  Blob: 'readonly',
  ArrayBuffer: 'readonly',
  JSON: 'readonly',
  Object: 'readonly',
  Array: 'readonly',
  Promise: 'readonly',
  RegExp: 'readonly',
  Date: 'readonly',
  Math: 'readonly',
  Number: 'readonly',
  String: 'readonly',
  Boolean: 'readonly',
  Error: 'readonly',
  TypeError: 'readonly',
  encodeURIComponent: 'readonly',
  decodeURIComponent: 'readonly',
  parseInt: 'readonly',
  parseFloat: 'readonly',
  isFinite: 'readonly',
  isNaN: 'readonly',
  CSS: 'readonly',
  getComputedStyle: 'readonly',
  MutationObserver: 'readonly',
  ResizeObserver: 'readonly',
  IntersectionObserver: 'readonly',
  AbortController: 'readonly',
  Event: 'readonly',
  EventTarget: 'readonly',
  Element: 'readonly',
  Node: 'readonly',
  NodeList: 'readonly',
  HTMLElement: 'readonly',
  HTMLDocument: 'readonly',
  location: 'readonly',
  navigator: 'readonly',
  history: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  performance: 'readonly',
  Image: 'readonly',
  Audio: 'readonly',
  btoa: 'readonly',
  atob: 'readonly',
  crypto: 'readonly',
  Intl: 'readonly',
  Map: 'readonly',
  Set: 'readonly',
  Symbol: 'readonly',
  Proxy: 'readonly',
  Reflect: 'readonly',
  WeakMap: 'readonly',
  WeakSet: 'readonly',
  Float32Array: 'readonly',
  Uint8Array: 'readonly',
  DataView: 'readonly',
  TextEncoder: 'readonly',
  TextDecoder: 'readonly',
  queueMicrotask: 'readonly',
  structuredClone: 'readonly',
  console: 'readonly',
  API: 'readonly',
  registerCleanup: 'readonly',
};

module.exports = [
  {
    ignores: [
      'server/public/app.js',
      'node_modules/',
      '*.min.js',
      'server/backups/',
    ],
  },
  {
    files: ['server/**/*.js', 'scripts/**/*.js', 'test/**/*.js', 'tests/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        require: 'readonly',
        module: 'readonly',
        exports: 'writable',
        process: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        Buffer: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
    },
  },
  {
    files: ['server/public/**/*.js', 'client/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...BROWSER_GLOBALS,
      },
    },
    rules: {
      'no-console': 'off',
    },
  },
  {
    files: ['extensions/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...BROWSER_GLOBALS,
      },
    },
    rules: {
      'no-console': 'off',
    },
  },
];
